# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- main: ./cmd/messanger/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  files:
  - init/messanger.service
checksum:
  name_template: 'checksums.txt'
dist: build/dist/
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  https://github.com/cohenjo/dbender
  description: A messanger - don't shoot it
  maintainer: Drunk DBAs <jony.cohenjo@gmail.com>
  license: MIT
  vendor: cohenjo
  formats:
  - deb
  - rpm
  recommends:
  - rpm
  bindir:  /usr/local/messanger/
  empty_folders:
  - /var/log/messanger

  files:
    "init/messanger.service": "/usr/lib/systemd/system/messanger.service"
  
